namespace ACalc
{
    [bindable]
    [default_interface]
    runtimeclass Subjects 
    {
        Subjects();
        Subjects(String subjectName, UInt8 classesAttended, UInt8 classesConducted);

        String SubjectName{ get; set; };
        UInt16 ClassesAttended{ get; set; };
        UInt16 ClassesConducted{ get; set; };
        Single DesiredPercentage{ get; set; };

        Single CurrentPercentage{ get; };
        Single RequiredPercentage{ get; };
        UInt16 ClassesNeeded{ get; };
    }
}
